### ISSUE TITLE
Disable normalisation from imaginary time evolution

### ISSUE THREAD

**Issue by stefDeNicola** [weinbe58/QuSpin#103]
I am looking at imaginary time evolution for the 2D quantum Ising model.
I perform the imaginary time evolution as

    times=np.arange(t_0,t_f+dt,dt)
    psi = HIsing2D.evolve(psi_0, 0.0,times,imag_time=True)

I would like to switch off the normalisation as knowledge of that is useful to me. By setting verbose=True I can get the normalisation as output, but is there any way to switch it off altogether/have it printed as a separate variable?

**Comment by weinbe58** [comment]
Hi! Unfortunately that feature is not implemented because typically the norm for a generic problem is very unstable.

If your problem has a time independent Hamiltonian (e.g. evolving with exp(-t H)) I would suggest to use the [exp_op](http://weinbe58.github.io/QuSpin/generated/quspin.operators.exp_op.html#quspin.operators.exp_op) class instead of evolve. This will calculate the matrix exponential without normalizing the state and should be a faster calculation as it will take advantage of the problem being static. To avoid instabilities you can also shift the Hamiltonian by the ground state energy so that the norm of the state remains finite during the evolution and then you can multiply by an extra factor of exp(-t E_gs) to get the properly normalized state. 

If your problem has a time dependent H than you can write your own function and use it with the [evolve](http://weinbe58.github.io/QuSpin/generated/quspin.tools.evolution.evolve.html#quspin.tools.evolution.evolve) function which is almost identical:

```
def imag_time_op(t,y,H):
    return -H.dot(y,time=t)

times=np.arange(t_0,t_f+dt,dt)
psi = evolve(psi_0, 0.0,times,imag_time_op,f_args=(H,))
```

Note that if H is a real matrix you can add `real=True` to the arguments of `evolve` to get faster code.

**Comment by stefDeNicola** [comment]
Many thanks!
