### ISSUE TITLE
bug with overwrite_v argument of expm_multiply_parallel

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#130]
`overwrite_v` optional argument does not work.

```
from quspin.tools.evolution import expm_multiply_parallel # Krylov-like evolution
import numpy as np
import scipy.sparse as sps

psi=np.zeros(10) 
psi[0]=1.0/np.sqrt(2.0)
psi[5]=1.0/np.sqrt(2.0)

times=np.linspace(0.2,20.0,10)

H_quench=sps.diags( np.cos(np.linspace(0.0,10,10)) )
work_array=np.zeros((2*len(psi),), dtype=np.float64)

expH_quench=expm_multiply_parallel(H_quench)

for j,t in enumerate(times):

	print(psi)

	expH_quench.set_a(-1j*t)
	expH_quench.dot(psi,work_array=work_array,overwrite_v=True)
	#psi=expH_quench.dot(psi)

	print(psi)

	exit()
```

**Comment by mgbukov** [comment]
btw, is the reason for the length of `work_array` to be twice the size of `psi` that it is real-valued? If yes, we should update the doc (and maybe throw a warning if someone passes a complex-valued `work_array`)

**Comment by weinbe58** [comment]
Oh the issue is your array is not the right type, since the resulting array should be complex your array you want to put in must be complex as well. I guess I forgot to put in an exception when this happens. 

And to answer your question:

I actually need two psi sized arrays to store intermediate results during the calculation.
