### ISSUE TITLE
Cython question 

### ISSUE THREAD

**Issue by Vutshi** [weinbe58/QuSpin#135]
Hi,
I am curious why do you have the cython generated code in an explicit form?
It seems to be more efficient to distribute cython code which is converted to cpp during installation like QuTiP does.

Best,
Denis

**Comment by weinbe58** [comment]
Hi Denis,

Since we're using conda to distribute the code we have to pre-compile the libraries and distribute the shared object files explicitly. If you want to look at the source you can look at it here on github; all the low level code will be contained in a directory called called _basis_..._core/ where ... is either 1d or general for the 1d and general basis respectively. 

Best,
Phil

**Comment by Vutshi** [comment]
Hi Phil,
Sorry, I was not clear. 
Why  `_basis_..._core/`  contains both .pyx and huge .cpp generated from the .pyx by some old cython? 
It seems to be more efficient to generate .cpp at the moment of `python setup.py install` with the latest cython version available during the installation.

Best,
Denis

**Comment by weinbe58** [comment]
Hi Denis,

Sorry for the late reply. Yes I remember now why I did this, its basically so that the user does not need Cython to actually compile the code from source. Its true that the cpp files are large, however, since we ship a set of p rebuilt binaries to Anaconda as our main platform for distributing the code, it doesn't make sense to worry about the huge cpp files. 

if you want to modify the *pyx files and get them to build, every extension setup.py file as a custom command: `python setup.py build_templates` which will call cython and compile the cpp files which you can then commit. 

Best,

Phil

**Comment by mgbukov** [comment]
fixed starting from v 0.3.1

**Comment by Vutshi** [comment]
Thank you!
