### ISSUE TITLE
ent_entropy

### ISSUE THREAD

**Issue by CattoG** [weinbe58/QuSpin#140]
I want to extract the reduced density matrix of a state using the ent_entropy tool, but I'm not able to print or use it. The code line is

S, S_A, rdm = ent_entropy(system_state=state, basis=basis, chain_subsys=[0,1,2,3],
                              return_rdm='A')

It says that 'rdm_A' is not defined, but if I ask to print(rdm) it says just 'rdm_A'.
Anyone knows where I'm wrong?

**Comment by CattoG** [comment]
Right, some code might help.
[ent_entropy.txt](https://github.com/weinbe58/QuSpin/files/2217156/ent_entropy.txt)
thanks

GC

**Comment by mgbukov** [comment]
Thanks! So there are two points to make here:

1) the ent_entopy function returns a python dictionary. A dictionary is a hash table: it is a one-to-oen mapping between the `keys` and the corresponding `values`. 

This means that you should use the function the following way:

```
# compute entanglement entropy and reduced density matrix
Sent_dict = ent_entropy(system_state=state, basis=basis, chain_subsys=[0,1,2,3],return_rdm='A')
print(type(Sent_dict))
# see all dictionary keys
print(Sent_dict.keys())
# extract the entanglement entropy of subsystem A
Sent = Sent_dict['Sent_A']
# extract the corresponding reduced dm
rdm_A = Sent_dict['rdm_A']
# print rdm_A
print(rdm_A)
```

2) we strongly recommend to use the new `basis.ent_entropy` function instead of the tools one. It gives the same result of course. This goes in a similar way:

```
Sent_dict = basis.ent_entropy(state, sub_sys_A=[0,1,2,3],return_rdm='A')
print(Sent_dict.keys())
```
and getting the values goes in the same way as above. 

A detailed example how to use `basis.ent_entropy` and all the arguments it accepts is given in Sec. 2.4 of the [new QuSpin tutorial paper](https://arxiv.org/pdf/1804.06782.pdf).

Additionally, you may want to [check the description](http://weinbe58.github.io/QuSpin/generated/quspin.basis.spin_basis_1d.html#quspin.basis.spin_basis_1d.ent_entropy) in the online documentation.

Let me know if this resolves the issue :)

Marin
