### ISSUE TITLE
Bug in exp_op_core.py - no iteration over operators possible

### ISSUE THREAD

**Issue by patryk-kubiczek** [weinbe58/QuSpin#146]
I have found a bug in the file exp_op_core.py which prevents iteration over operators on which exp_op act. Namely, the order of arguments for the function _`hamiltonian_iter_dot` is inconsistent within the code. 

In the lines 489 and 504 the order is
` _hamiltonian_iter_dot(M, other, self._step, self._grid)`
while in the line 750 it is
`_hamiltonian_iter_dot(M, other, grid, step)`

It's an easy fix.

**Comment by weinbe58** [comment]
Thanks, It will be fixed in the next release!

**Comment by mgbukov** [comment]
@weinbe58 I think there's still a bug left with the general `get_proj` and `get_vec` functions. 

I got an email today from a guy using the `spinless_fermion_general` reporting a mismatch in the dimensions of the projector (compared to the case w/o symmetries). I'm attaching a script showing the mismatch.

It's likely some array size preallocation issue with `get_proj`, because the guy said "There are lots of zeros values in the full basis wavefunction. After deleting the zeros, I can get the correct wavefuntion."

Here's the script:
[ED2DSpinless.txt](https://github.com/weinbe58/QuSpin/files/2717812/ED2DSpinless.txt)
