### ISSUE TITLE
some questions about Floquet tutorial

### ISSUE THREAD

**Issue by Chapa1** [weinbe58/QuSpin#188]
Dear the creators of QuSpin!
I have a couple of equestions.
1) What is the aim to add np.finfo(float).eps to t_list in the tutorial?
http://weinbe58.github.io/QuSpin/generated/quspin.tools.Floquet.Floquet.html?highlight=floquet
2) the second question is about the choice of t_list and dt_list in the same tutorial.
t_list=np.array([0.0,t.T/4.0,3.0*t.T/4.0])
dt_list=np.array([t.T/4.0,t.T/2.0,t.T/4.0]) 
We divided the interval T by 3 parts: [0,T/4], [T/4,3T/4] and [3T/4,T] with t_0=0,   t_1=T/4,   t_2=3T/4 and t_3=T.
Is it true that we chose dt in dt_list as follows
dt1=t_1-t_0=T/4 ,     dt2=t_2-t_1=T/2       and    dt3=t_3-t_2=T/4?

I thought that the smaller dt, the more accurate the time-evolution we obtain. why you chose only 3 intervals and not, for example, 30?

3) The same tutorial.
Is it true that the overlap of a state psi_0 with, say, the first Floquet-state can be calculated via
v0=VF[:,0]
np.dot(np.conj(psi_0),v0)?
without any np.transpose(psi_0)?
It seems that, for example, both 
v1=VF[:,1] and v1=np.transpose(VF[:,1])
gives the same result for 
np.dot(np.conj(v1),v0) 

4) You make use of psi_0=psi_0.reshape((-1,)) 
at the end of the tutorial 
http://weinbe58.github.io/QuSpin/examples/example0.html?highlight=exact
what does it mean? I understand what .reshape((-1,)) do for a matrix. But for a vector it seems it does nothing.

Thank you in advance!

**Comment by mgbukov** [comment]
1. The time-dependence in line 16 uses a periodic step function due to `np.sign()`. Adding `np.finfo(float).eps` makes sure the step function is evaluated always on the right side of the step. It's like taking the limit from the right. If we don't do this, by chance (i.e. machine precision) the drive might get evaluated at the left side of the step but we don't want this, or we'll break the periodicity.

2. Yes, this is true.

You can only improve the accuracy by decreasing `dt` if the drive is not piece-wise constant. For piece-wise constant drives, u actually gain computational efficiency because there is no need to evaluate a time-ordered exponential (the drive is piece-wise constant).  Note that for non piece-wise constant drives (e.g. cos or sin) u can use option (i) of `evo_dict` (see doc). 

3. Yes, no need for an explicit transpose here, if `psi_0` is a one-dimensional array, because numpy doesn't care about it. Alternatively, you can use `psi_0.coni().dot(v0)`.

Note that you do need the transpose if your objects are matrices. 

4. This gets rid of redundant array dimensions. 

Try printing `psi_0.shape` before and after the line `psi_0=psi_0.reshape((-1,))` to see the difference. 

To understand what the two mean, print the array `psi_0` in both cases. In one case u'll notice an extra pair of `[]`, which we remove with this line of code.

**Comment by Chapa1** [comment]
Thank you very much for the exhaustive answer, Marin.
I have another question.
I want to calculate the quasienergies and Floquet states for the hamiltonian with complex coefficitents:
the hamiltonian has terms like exp(i*theta) c_j c^{\dagger}_{j+1} + h.c., with `i`  being an imaginary unit and c being a fermionic operator, and \theta is small.
If I construct directly this hamiltonian, I get an error
OpstrError: attemping to use real hamiltonian with complex matrix elements.
Is it possible to curcumvent this problem?
One can, for example, set \lambda=exp(i*theta) and 1/lambda =exp(-i*theta) with real lambda and some quantities (which I want to calculate using Floquet states and quasienergies) multiply by `i`, but the Hamiltonian obtained will be non-hermitian.

**Comment by Chapa1** [comment]
I think 
hamiltonian(static,dynamic,dtype=np.complex128,basis=basis)
is the answer.
