### ISSUE TITLE
Linux Mint 18.3: Error in calculating expectation value

### ISSUE THREAD

**Issue by DarthMalloc** [weinbe58/QuSpin#222]
I am trying to calculate an expectation value for a 1D transverse field Ising chain, and my code is as follows (The indentations for the evolve_gen function do not show up in my post, but they are in the code itself):

`L_1d = 16`
`Omega = 2.0`
`def evolve_gen(psi0, nT, U):`
`    yield psi0`
`    for i in range(nT):`
`        psi0 = U.dot(psi0)`
`        yield psi0`
`basis_1d = spin_basis_1d(L_1d, kblock=0, pblock=1, zblock=1)`
`X_1D = [[1.0, i] for i in range(L_1d)]`
`X_1D_list = [["x", X_1D]]`
`X_op_1D = hamiltonian(X_1D_list, [], basis=basis_1d, dtype=np.float64, check_symm=False)`

`J_zz_1d_sc = [[-0.5, i, (i+1)%L_1d] for i in range(L_1d)]`
`hx_1d_sc = [[-1.0, i] for i in range(L_1d)]`
`H_1d_sc = hamiltonian([["zz", J_zz_1d_sc], ["x", hx_1d_sc]],[], basis=basis_1d, dtype=np.float64, check_symm=False)
`
`J_zz_1d_c = [[-1.0, i, (i+1)%L_1d] for i in range(L_1d)]`
`hx_1d_c = [[-1.0, i] for i in range(L_1d)]`
`H_1d_c = hamiltonian([["zz", J_zz_1d_c], ["x", hx_1d_c]], [], basis=basis_1d, dtype=np.float64, check_symm=False)`

`nT = 200`
`t = Floquet_t_vec(Omega, nT, len_T=1)`
`[E_1d_min_sc], psi_1d_sc = H_1d_sc.eigsh(k=1, which="SA")`
`psi0_1d_sc = psi_1d_sc.ravel()`
`Ham_1d = exp_op(H_1d_c, a=-1j)`
`psi_1d_sc_t = evolve_gen(psi0_1d_sc, nT, Ham_1d)`
`Obs_1dX_sc_t = obs_vs_time(psi_1d_sc_t, t.vals, dict(E=X_op_1D), return_state=True)`

For some reason, when I run this, I get the following error:

Obs_1dX_sc_t = obs_vs_time(psi_1d_sc_t, t.vals, dict(E=X_op_1D), return_state=True)

  File "/usr/lib/python3.7/site-packages/quspin/tools/measurements.py", line 692, in obs_vs_time
    psi_t = _np.squeeze(_np.dstack(psi_t_list))

  File "/usr/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 699, in dstack
    return _nx.concatenate([atleast_3d(_m) for _m in tup], 2)

ValueError: need at least one array to concatenate
There is clearly some detail that I've overlooked, but I can't seem to spot it. If anyone would be willing to help, I would really appreciate it.

**Comment by mgbukov** [comment]
I can't reproduce this bug. Your code (see attached .txt file) runs on my computer properly.

It looks like a numpy issue to me. If u run `obs_vs_time_bug.txt`, in line 12 it will print your numpy version. My version is `1.15.4`, if yours is lower, try updating and see if this resolves the issue. 

[obs_vs_time_bug.txt](https://github.com/weinbe58/QuSpin/files/3288888/obs_vs_time_bug.txt)

**Comment by DarthMalloc** [comment]
Thank you very much for getting back to me. I seem to have found a solution for this issue. There was just one more thing that I wanted to check with you. I was wondering, in particular, how to get the results of measurement collapse using the obs_vs_time function (does it involve the psi_time component of the dictionary returned by the function), as well as the optimal way to write those results to a file (I know that simply writing to a text file probably isn't ideal).

**Comment by mgbukov** [comment]
Yes, obs_vs_time evolves the state \\psi(t) and measures the observable O(t) in it. Then, if requested it also returns the state. The expectation it computes is

\\langle\\psi(t)|\\mathcal{O}(t)|\\psi(t)\\rangle

If the state and/or operator is time-independent, it computes the corresponding special case. 

I typically use pickl to store data in python. Not sure if this is optimal though.

**Comment by DarthMalloc** [comment]
Thank you very much. That helps a lot. Sorry about the delay. When checking the length of the psi_time element of the result returned by obs_vs_time with return_state set to True, I noticed that the length was equal to the number of eigenvectors belonging to the observable. Is this because the measurement occurring is a projective measurement?

**Comment by mgbukov** [comment]
If I remember correctly, the vector psi_time should be of shape (H_dim,n_times_steps), where n_time_steps is the number of time steps in the time vector ist, and H_dim the dimension of the Hilbert space. 

Your observation is also correct because the number of eigenvectors belonging to the observable is the same as the Hilbert space dimension. 

However, the vector psi_time is _not_ the projective measurement result. The projective measurement result is stored in the custom keys of the dictionary which is used to pass the operators to `obs_vs_time()`.

**Comment by DarthMalloc** [comment]
I think I understand. When you mention the projective measurement result, are you referring to the expectation value? Also, does what you are saying mean that the state that is stored in the psi_t element is equal to P|\psi(t)\rangle / \langle \psi(t)|P|\psi(t)\rangle? If not, I am wondering how I can recover that result from the return value, and whether there is a way to get the actual collapse results in QuSpin.

**Comment by DarthMalloc** [comment]
I think I understand. When you mention the projective measurement result, are you referring to the expectation value? Also, does what you are saying mean that the state that is stored in the psi_t element is equal to P|\psi(t)\rangle / \langle \psi(t)|P|\psi(t)\rangle? If not, I am wondering how I can recover that result from the return value, and whether there is a way to get the actual collapse results in QuSpin.

**Comment by weinbe58** [comment]
wrong thread guys haha!

**Comment by mgbukov** [comment]
*When you mention the projective measurement result, are you referring to the expectation value?*

​Yes, the expectation value is defined just t​he way you do that in introductory quantum mechanics textbooks.

*Also, does what you are saying mean that the state that is stored in the psi_t element is equal to P|\psi(t)\rangle / \langle \psi(t)|P|\psi(t)\rangle?*

 No, the state stored i​s in\psi_t` is ​NOT P|\psi(t)\rangle / \langle \psi(t)|P|\psi(t)\rangle​​. The way to think about what quspin does is the following: say you can run your experiments as much as you want, and you can measure the exact expectation value at any time. Then obs_vs_time() measuring at different times means that you would run your experiment from the beginning and stop it at the desired time to measure the observable. To get the value of the measurement at the next time, you run the experiment again, from the beginning, and you stop at the next time to measure, etc. Note that this measurement gives you the exact expectation value, i.e. every single measurement assumes you run the experiment infinitely many times so that the statistical variance is zero. 

*If not, I am wondering how I can recover that result from the return value, and whether there is a way to get the actual collapse results in QuSpin.*

To obtain P|\psi(t)\rangle / \langle \psi(t)|P|\psi(t)\rangle​​, all you need to do is 
(i) define the operator P
(ii) loop over the states psi_t and compute this quantity. 

You don't need obs_vs_time for this. The following example shows you how to do this (but you need to change P to be the specific projector you want to consider)

```
from __future__ import print_function, division
#
import sys,os
quspin_path = os.path.join(os.getcwd(),"./QuSpin/")
sys.path.insert(0,quspin_path)
#
from quspin.operators import hamiltonian # Hamiltonians and operators
from quspin.basis import spin_basis_1d # Hilbert space spin basis
from quspin.tools.measurements import obs_vs_time
import numpy as np # generic math functions
#
L=12 # syste size
# coupling strenghts
J=1.0 # spin-spin coupling
h=0.8945 # x-field strength
g=0.945 # z-field strength
# create site-coupling lists
J_zz=[[J,i,(i+1)%L] for i in range(L)] # PBC
x_field=[[h,i] for i in range(L)]
z_field=[[g,i] for i in range(L)]
# create static and dynamic lists
static_1=[["x",x_field],["z",z_field]]
static_2=[["zz",J_zz],["x",x_field],["z",z_field]]
dynamic=[]
# create spin-1/2 basis
basis=spin_basis_1d(L,kblock=0,pblock=1)
# set up Hamiltonian
H1=hamiltonian(static_1,dynamic,basis=basis,dtype=np.float64)
H2=hamiltonian(static_2,dynamic,basis=basis,dtype=np.float64)
# compute eigensystems of H1 and H2
E1,V1=H1.eigh()
psi1=V1[:,14] # pick any state as initial state
E2,V2=H2.eigh()
#
# time-evolve state under H2
times=np.linspace(0.0,5.0,10)
psi1_t=H2.evolve(psi1,0.0,times,iterate=True)
# calculate  P|\psi(t)\rangle / \langle \psi(t)|P|\psi(t)\rangle
P=H1 # change to your projector
result=np.zeros((basis.Ns,times.shape[0]),dtype=np.complex128)
for j,psi in enumerate(psi1_t):
	result[:,j]=P.dot(psi)/P.expt_value(psi)
print(result.shape)
```

**Comment by DarthMalloc** [comment]
Thank you for clarifying that. I should have been more specific about what I am trying to do. I am trying to get projective measurements for a single-qubit system. I was already familiar with the formula for calculating projective measurements. The reason that I was trying to calculate the projective measurement results using obs_vs_time is because I was originally hoping to get the projectors from the eigenstates of the observable, but when I tried to get them using eigsh, using the following code,
L = 1
Z = [[1.0, i] for i in range(L)]
Z_list = [["z", Z]]
Z_op = hamiltonian(Z_list, [], basis=basis_1d, dtype=np.float64, check_symm=False)
E_z, V_z = Z_op.eigsh(maxiter=100000000)

I get this error:

TypeError: Cannot use scipy.linalg.eigh for sparse A with k >= N. Use scipy.linalg.eigh(A.toarray()) or reduce k.

It is not clear how this error could have occurred, since the 2x2 Pauli Z operator should have two eigenvectors.

**Comment by mgbukov** [comment]
H.eigsh() computes the k lowest eigenvalues but never all of them. Since
your operator has only two eigenvalues you get an error.

Try using H.eigh() instead, which co oues all eigenvalues, and you'll be
fine.

See example0.py in the list of examples in the quspin documentation page to
see the difference.

Marin
