### ISSUE TITLE
Construct tensor_basis with fixed total number of particles

### ISSUE THREAD

**Issue by HumpyBlumpy** [weinbe58/QuSpin#273]
Hello,

I am using tensor_basis to construct a basis for a spin-boson Hamiltonian where I have 1 spin coupled to a 1D array of bosons. 

I would like to constrain the basis states based on the total number of particles defined as $\sum_x a_x^\dagger a_x + \sigma_+\sigma_-$. 
Based on the note in the documentation 
> The tensor_basis class does not allow one to make use of symmetries, save for particle conservation.

it seems that it should be doable, but I haven't found how to do it.

Here is my current code:
```
##### setting parameters for simulation
# physical parameters
Lb = 10 #boson system size
Ls = 1 #spin system size
J = 0.1 # hopping strength
omega0 = 1 # boson on site energy
Delta = 1 # spin on site energy
spin_boson_num = 0 #boson site coupling index

###### create the basis
bosons = boson_basis_1d(Lb,Nb=[0,1])
spin = spin_basis_1d(Ls)
basis = tensor_basis(spin,bosons)
#print(basis)

glist = np.linspace(0,1,10)
hop = [[-J,i,i+1] for i in range(Lb-1)] # hopping 
onsite_bosons = [[omega0,i] for i in range(Lb)] # onsite energy
onsite_spins = [[Delta/2,i] for i in range(Ls)] # onsite energy

eigs_list =[]
for g in glist:

    spin_boson_int = [[g,0,spin_boson_num]] 
    
    # create static lists
    static = [
              ["|+-", hop], # up hop left
              ["|-+", hop], # up hop right
              ["|n", onsite_bosons], # 
              ["z|", onsite_spins], # down hop right
              ["+|-", spin_boson_int], # onsite interaction       
              ["-|+", spin_boson_int] # onsite interaction
             ]
    #print(static)
    #
    ###### setting up operators	
    # set up hamiltonian dictionary and observable (imbalance I)
    no_checks = dict(check_pcon=False,check_symm=False,check_herm=False)
    H = hamiltonian(static,[],basis=basis,**no_checks)
    eigs_list.append(H.eigvalsh())
    #print(np.matrix(H.toarray()))
    
plt.figure()
plt.plot(glist,eigs_list)
plt.show()
```

**Comment by weinbe58** [comment]
The problem is the `tensor_basis` is implemented fully in python and does not actually know anything about the basis objects that are passed into it except how to construct matrix elements. As such it is not possible to do global symmetries of the tensored basis. 

If it is really important to implement this symmetry then the best option would be to try out the [user_basis](http://weinbe58.github.io/QuSpin/user_basis.html)

How it might look complicated at first but there are a few examples that explain how to implement some standard things. Once you get the hang of it you can really do a lot. You can even implement lattice symmetries for your model.
