### ISSUE TITLE
number of sites attribute does not work in tensor_basis

### ISSUE THREAD

**Issue by HumpyBlumpy** [weinbe58/QuSpin#274]
In the documentation of tensor_basis it is stated that N is an attribute:
> N | int: number of sites the basis is constructed with.

However, calling basis.N yields an error 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-4df90e95dda6> in <module>
----> 1 basis.N

~/anaconda3/lib/python3.7/site-packages/quspin/basis/base.py in N(self)
     87         def N(self):
     88                 """int: number of sites the basis is constructed with."""
---> 89                 return self._N
     90 
     91         @property

AttributeError: 'tensor_basis' object has no attribute '_N'
```

**Comment by weinbe58** [comment]
Hi, So I guess I never foresaw anyone needing to use `N` in the tensor basis, The main problem being, which `N` to return since there are at least 2 numbers. 

I'm adding a special property for the tensor basis, the `N` property returns a tuple of integers corresponding to the system sizes of all of the basis objects in the tensor basis, so for your code if you have two basis objects tensored together, the `N` property is a tuple with two integers the first integer corresponding to the first basis and the second integer corresponding to the second basis.
