### ISSUE TITLE
possible bug in make_basis code

### ISSUE THREAD

**Issue by jaredjeya** [weinbe58/QuSpin#303]
Hi,

I've been trying to use spin_basis_general for my system which has zA/zB symmetry (inversion on odd or even sites respectively), as well as parity, and translational invariance if periodic. 
Thanks for the help with #296.  

I'm trying to rewrite my code to use spin_basis_general, and my code for defining the symmetries currently looks like:

    i = np.arange(self.L, dtype=int)  		# List of sites
    T = (i + 1) % self.L  				# Translation
    P = (self.L - 1) - i  				# Parity inversion
    Z = -(i + 1)  					# Total spin inversion
    ZA = np.zeros_like(i)  				# Odd site spin inversion
    ZB = np.zeros_like(i)  				# Even site spin inversion
    ZA[0::2]** = Z[0::2]`
    ZA[1::2] = i[1::2]`
    ZB[0::2] = i[0::2]`
    ZB[1::2] = Z[1::2]

and then I define the blocks e.g `blocks["zAblock"] = (ZA, 0)`, followed by...

`return spin_basis_general(self.L, S="1/2", pauli=1, **blocks)`

However, when I try to use zA/zB symmetries, I get an error:

`ValueError: estimate for size of reduced Hilbert-space is too low, please double check that transformation mappings are correct or use 'Ns_block_est' argument to give an upper bound of the block`

I've debugged the python portion of the code and it seems that the line

`Ns = self._core.make_basis(basis,n,Np=self._Np)`

in `base_general.basis_general.make()` returns -1. This is then C++ code so I can't go any further without an in-depth understanding of the code.

I've tried passing `Ns_block_est = 2**L` and this avoids the error, but this is probably not great for memory: it's especially strange given the end result (with zA and zB set) is a block of size (2^L)/4, which is exactly the estimate QuSpin makes. In fact, I've just tried `Ns_block_est = 2**L//4 + 1` and it's perfectly happy, which makes me think maybe there's an off-by-one error in the code somewhere. Is this a bug? Or is it just that QuSpin needs a bit more help with non-standard symmetries?

Any help much appreciated.

**Comment by weinbe58** [comment]
Hi @jaredjeya 

First, I think you have to be a bit careful here, for chains with even numbers of sites you can't combine parity with Z_A + Z_B symmetries because parity flips sublattice A to sublattice B. 

Second, the estimate for the hulbert space is not full-proof, generally the sector size will be approximately given as the total hilbert space divided by the number of possible quantum number combinations but some sectors will have more or less states. We try out best to estimate it but sometimes it doesn't work. This doesn't neccesarily mean there is a bug with QuSpin but most likely the estimate failed and you need to guess it yourself.

If you're concerned that the symmetries are wrong you can always diagonalize a smaller system  without symmetries to get an unbiased result and compare that to your symmetry code. 

Hope this helps

Best,

Phil

**Comment by mgbukov** [comment]
@jaredjeya did this resolve the problem?

**Comment by jaredjeya** [comment]
Hi, yes, I think it did (I just give it an estimate that's 10% larger than the naive estimate and it seems to be happy with that). Thanks!
