### ISSUE TITLE
User_basis for highly constrained models

### ISSUE THREAD

**Issue by TorstenZache** [weinbe58/QuSpin#317]
Hi,

I have two questions about the functionality of the user_basis. I use the pre_check_state function for implementing models with local symmetries by discarding the unwanted states. But the number of desired states is extremely small compared to the full Hilbert space I start with. As a consequence I quickly run out of integer representations for the states. Currently the user_basis only supports int32 and int64 as basis_dtype. Could you extend the functionality by including the custom large integers which are available for the *_basis_general classes?

My second question is related to that issue. Currently, the part of my code where the basis is constructed is much slower than setting up the Hamiltonian or any of the following calculations, so I am looking for ways to speed it up. Presumably I can improve it significantly by writing the constraints for pre_check_state with binary operations, but I haven't figured that out yet. If I understand it correctly, QuSpin loops over all possible states one-by-one using the next_state function and then decides to include/discard via pre_check_state. So another possible speed-up would be a parallelisation of this calculation. Is this possible within the current version of QuSpin?

Cheers,
Torsten

**Comment by mgbukov** [comment]
I believe, the problem with using larger integers is that neither `numpy/scipy` nor `numba` have support for large integers. For this, you'd likely have to mess up with the `cpp` part of quspin, unless there's some trick. @weinbe58 , what do u think?

Actually, one possibility (but I don't know if this is feasible), is to generate your basis by some means, convert the final basis states to chars (that's the numpy format for large integers in the general basis), and then import your custom basis in the general basis class. This import means that you would have to overwrite all the private attributes of the `basis_general` class manually. 

For the second Q -- yes, if you have a two-dimensional on-site Hilbert space (spins), I am almost 100% positive you will be able to find a good binary operation to discard states in `pre_check_state`, and this will give you a lot of speedup. But it seems to me that the above issue with storing the states is more severe. 

About the parallelization, you may want to look up the `numba` documentation to see if there are options to parallelize the loop; I think I have seen something similar there some time ago.

**Comment by weinbe58** [comment]
To the first question, unfortunately, there is currently no plan to expand the integer sizes to that which are used in the rest of the general_basis classes. One workaround would be to change the underlying representation to make it fit within the range of integer values. 

As for the question of parallelization, yes you're are correct the pre_check_state process should also be parallelized. I think the current code is defaulting to sequential code because it uses the number of symmetries to determine to parallelize, so if there are no symmetries is falls back to non-parallel code. Historically this choice was for efficient because if there are no symmetries we know each encountered state is a reference state, but this is no longer the case with the pre_check_state function. 

in issue #318 I talk about a workaround for this if you're not planning on implementing any symmetries with your basis, otherwise, if you implement symmetries the code will run the parallel code automatically.

**Comment by TorstenZache** [comment]
Thanks for your help!

Your workaround from #318 already helps a bit.
I have to see how far I can get without using larger integers.

**Comment by TorstenZache** [comment]
I have another related question:
Is there is a simple way to save and load a "pre_checked" user_basis? I would like to avoid constructing the basis over and over again for several independent simulations with the same system size.

**Comment by weinbe58** [comment]
Unfortunately you can't pickle the `user_basis` class, however you can save your basis array and then use another `user_basis` class that can import that array, follow [this](http://weinbe58.github.io/QuSpin/examples/example16.html#example16-label) example.

**Comment by weinbe58** [comment]
the basis array is stored as the attribute `basis.states` which you can save directly using NumPy saving methods.
