### ISSUE TITLE
inter-species anticommutation relations incorrect

### ISSUE THREAD

**Issue by Fysiker007** [weinbe58/QuSpin#330]
Hello!

When I try to create a tensor product of two spinless_fermion_basis_1d, or when I use spinful_fermion_basis_1d, it seems that the intra-species anticommutation relations are satisfied but not the inter-species anticommutation relations.

For example, if we consider two pieces (up and down), then the Hermitian conjugate of c_{u,1} c_{u,2}^dag c_{u,3} c_{d,4}^dag should be c_{d,4} c_{u,3}^dag c_{u,2} c_{u,1}^dag = c_{u,1}^dag c_{u,2} c_{u,3}^dag c_{d,4}. In QuSpin, I would therefore code this as

```
L = 4
J = 1.0
dynamic = []
basis_psi1 = spinless_fermion_basis_1d(L=L)
basis_psi2 = spinless_fermion_basis_1d(L=L)
basis = tensor_basis(basis_psi1,basis_psi2)

tunneling = [[J,i,(i+1)%L,(i+2)%L,(i+3)%L] for i in range(L)]
static = [["+-+|-",tunneling],["-+-|+",tunneling]]
H = hamiltonian(static,dynamic,basis=basis)
```

but this leads to the following error:

```
test.py:39: UserWarning: The following static operator strings contain non-hermitian couplings: ['-++|-', '++-|-', '--+|+', '-+-|+', '+--|+', '+-+|-']
  H = hamiltonian(static,dynamic,basis=basis)
```

**Comment by weinbe58** [comment]
This is a known issue, however, I think a warning would be very useful.

**Comment by mgbukov** [comment]
Yes, in fact, we wanted to keep it this way deliberately to be able to cover the case of two DIStinguishable fermion species (might occur in ultracold gases where different atomic isotopes are used). Distinguishability means the inter-species commutation relation is bosonic while the intra-species commutation is fermionic (each species is a fermion). 

But we should put a note on this in the documentation in the next release.

**Comment by Fysiker007** [comment]
Thanks for the information. Do you know of a scenario when this inter-species distinguishability would be interesting?

**Comment by mgbukov** [comment]
@Fysiker007 e.g., if you have a mixture of fermions (Fermi-Fermi mixture) where the two species have different masses then they are distinguishable. I think there is some literature out there on Fermi-Fermi mixtures in the context of cold atoms; In high energy physics, protons and neutrons are distinguishable fermions. I'm sure there are other situations because "interesting" depends on who you talk to :) 

In quspin, if you ever need to couple two spinful fermions species (so that all fermions anticommute), one way to do this is to use the `spinful_fermion_basis_general` with `advanced` notation, and consider two sublattices (one per species). Then you can put interactions between fermions sitting on different sublattices which would be equivalent to on-site inter-species interactions. It's like standard band theory where two bands are equivalent to two fermion species (one per band), just the many-body version of it. You won't get to too large system sizes, though.

**Comment by Fysiker007** [comment]
OK I see. Thanks for the tip on `spinful_fermion_basis_general` :)

**Comment by mgbukov** [comment]
I leave this open until we add the note to the `tensor_basis`. Otherwise, someone else might get confused too.

**Comment by mgbukov** [comment]
I added a note in tensor.py
