### ISSUE TITLE
Nonhermitian time evolution

### ISSUE THREAD

**Issue by HumpyBlumpy** [weinbe58/QuSpin#336]
Hello,

Is it possible to perform time evolution with a non-hermitian Hamiltonian?

This would be useful, for example, for simulation Lindblad time evolution using the trajectories method https://arxiv.org/abs/1405.6694

**Comment by mgbukov** [comment]
Yes, you can check the example of Lindblad dynamics in the online
documentation.

To construct non-hermitian operators, set check_herm=False in the
haniltonian constructor.

**Comment by HumpyBlumpy** [comment]
Thanks.
I saw the Lindblad example, but I want to do is to evolve a wavefunction (not density matrix) with nonhermitian Hamiltonian and apply jumps and average over such trajectories.

I guess what I am asking for, is out of the different ways to apply time evolution in QuSpin, which of them can handle a nonhermitian Hamiltonian?
In the Lindblad example, you are using the .evolve function, which as far as I understand is simply an ODE solver.
Would exp_op work for nonhermitian Hamiltonian ? In the documentation it says that exp_op is implemented using the Taylor series so I would guess that it should work.
How about expm_multiply_parallel?
I think the Lanczos method would not work?

and which method would be the best for this purpose?

Thanks for your help!

**Comment by weinbe58** [comment]
@HumpyBlumpy, you should be able to simply use the `evolve` functino in `quspin.tools.evolution` but you have to normalize the state by using the 'imag_time=True`.All this option does is to normalize the state after the solver is called. Unfortunately, the solver used by quspin does not normalize the state automatically so if you're evolving your system for long periods of time you have to make sure to call the evolve function with many time points between the initial and final time so that the function can normalize the state.
