### ISSUE TITLE
Quspin installation issue 

### ISSUE THREAD

**Issue by mahaveer-thalor** [weinbe58/QuSpin#359]
![20201021_235149](https://user-images.githubusercontent.com/73251091/96766558-e5041800-13f8-11eb-9a71-13e4e95c5941.jpg)
 hey developers,
I used the commond "conda install -c weinbe58 quspin" to install quspin. I have python 3.8. But i am facing the difficulty which is attached in jpg file.  Please suggest how it can be fixed

**Comment by mgbukov** [comment]
quspin currently does not have a pre-compiled version for py38. This is because, back in April when we did the current release, conda build did not support py38. 

We will certainly try to include a py38 version in the next release. 

Dor the time being, you can downgrade python to 3.7 (or create an environment with python 3.7)

**Comment by mahaveer-thalor** [comment]
Thanks, i downgraded python to 3.7 version and installed miniconda instead of anaconda3, now everything working fine.
I think there is a issue with anaconda3 latest that it has numba 0.50 version which also cause other problems while running code, couldnt able to downgrade numba to <=0.48 with anaconda3 so i had to go with miniconda.

**Comment by mgbukov** [comment]
Yes there is a problem with numba in that they release new versions which
are not backwards compatible.

Marin
