### ISSUE TITLE
Calculation of Emin on changing of hz in example0.py

### ISSUE THREAD

**Issue by sachin00-github** [weinbe58/QuSpin#370]
**example0.py find the eigenstates and energies of the XXZ chain.**
There are 3 modules for computing spin-1/2 basis
 `basis = spin_basis_1d(L,pauli=False)`
`#basis = spin_basis_1d(L,pauli=False,Nup=L//2) # zero magnetisation sector`
`#basis = spin_basis_1d(L,pauli=False,Nup=L//2,pblock=1) # and positive parity sector`

I am checking  **only** `Emin` on changing the `hz (ext . mag field)`.

Problem is that I get different `Emin` for different `hz` only when I use the first module for basis,
and for two other basis, I get same  `Emin` for different `hz` .

I will appreciate your help.

**Comment by weinbe58** [comment]
Hi @sachin00-github,

The issue is in the latter two basis instantiations, you are picking the total Sz projection to be fixed to 0, while in the first basis you do not. for uniform hz, the operator couples to the total Sz of the system so if the total projection os 0 then the operator that couples to hz is always 0 and so by changing hz you do not change the energy of any eigenstates.

**Comment by sachin00-github** [comment]
Thanks for your reply.

could you please answer the following, 


A) if hz remains zero, then what is the purpose of last two basis as we cannot find energies and other properties as a function of hz. ?
B) If I try to find Emin using first basis for a fixed hz for L larger than 20 or so, then it gets killed automatically after some time, without giving the results, and it utilises one one core of my desktop even after specifying the cores around 10. 

Pl clarify, I will appreciate your time.

**Comment by weinbe58** [comment]
to Answer your questions A and B can go together.

The idea is that the total Sz of the system is a conserved quantity so each eigenstate can be parameterized by both their energy and their total Sz projection. Because you know this you can more easily find the Emin by finding the Emin for each value of Sz projection and then picking the sector with the smallest value.

**Comment by mgbukov** [comment]
> A) if hz remains zero for last two basis, then what is the purpose of last two basis as we cannot find energies and other properties as a function of hz. ?

`example0.py` is not meant to necessarily be a physically meaningful example, as ou vary the couplings. It is there to present the user with the basic quspin functionality, i.e. to showcase how symmetries are implemented. Users would have to come up with their own interesting applications of quspin. Sorry about the confusion!

> B) If I try to find Emin using first basis for a fixed hz for L larger than 20 or so, then the job gets killed automatically after some time, without giving the results, and it utilises only one core of my desktop even after specifying the cores around 10.

This suggests that your machine does not have the required resources to sustain the `L>20` simulation. This is common with exact diagonalization (ED) where the Hilbert space size grows exponentially with `L`. 

* you may want to check if the code runs OK up to the point where you compute Emin. This would mean that the issue comes from diagonalizing too large of a matrix, not from constructing the matrix, or constructing the basis. Increaseing further `L`, you will eventually see how the `hamiltonian` class fails to do its job (due to lack of resources) and ultimately also the `basis` constructor will also fail.
* since you also mention cores, I assume you were expecting to see some parallelization speed here. Note two things: (i) you **need** to install the `omp` version of quspin to make use of multiple omp-threads, and you need a machine that supports this; (ii) only the `basis` and `hamiltonian` are `omp` parallelized; the diagonalization routines are trivial wrappers over `numpy` and `scipy` and cannot be sped up using more `omp` processes; they _might_ be amenable to a speed-up using MKL, see [here](https://weinbe58.github.io/QuSpin/parallelization.html#parallel-computing-support).

**Comment by sachin00-github** [comment]
Ok!, Thanks for your reply.
