### ISSUE TITLE
Issue with hamiltonian matrix element generation 

### ISSUE THREAD

**Issue by kaushman1996** [weinbe58/QuSpin#376]
Dear Developers
I am encountering a weird error. I am evaluating eigenvalues of a very simple Hamiltonian lets say
 c†↑c↑-c†↓c↓ at site number 0 
Now I am evaluating its eigenvalue and  printing its 10th eigenvalue.

But the problem is each different run(for this I am using for loop), I gets different answer fluctuating between 0 and 1.

A very simple code is here. Please have a look, and let me know, what serious basic problem is going on here.

`from quspin.basis import spinful_fermion_basis_general  

from quspin.operators import hamiltonian 
import numpy as np 
for i in range(10):
    L=10    #number of sites
    basis=spinful_fermion_basis_general(L,double_occupancy=False,Nf=[(2,2),(1,3),(3,1),(4,0),(0,4)])
    static=[["+-|",[[1,0,0]]],["|+-",[[-1,0,0]]]]
    H=hamiltonian(static,[],basis=basis,dtype=np.float64,check_pcon=False,check_herm=True)
    E,ww=H.eigsh(k=10,which='SA',maxiter=1E10,return_eigenvectors=True)
    print(E[9])`

**Comment by mgbukov** [comment]
This is not a problem with quspin; it's related to how the [`eigsh`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html) is meant to work. 

Note first that you can take lines
```
L=10 #number of sites
basis=spinful_fermion_basis_general(L,double_occupancy=False,Nf=[(2,2),(1,3),(3,1),(4,0),(0,4)])
static=[["+-|",[[1,0,0]]],["|+-",[[-1,0,0]]]]
H=hamiltonian(static,[],basis=basis,dtype=np.float64,check_pcon=False,check_herm=True)
```
outside the `for` loop and you'll still get the same inconsistent behavior. Moreover the same is unrelated to whether u compute the e'vectors or not. 

Note also that if you replace the `eigsh()` routine by the `eigvalsh()` routine which computes the entire specturm, the inconsistency goes away, i.e. you get correct consistently the same results. This means that it's an issue with `eigsh()`, bot `basis` or `hamiltonian`.

Now, the way `eigsh()` works is it starts from a random vector in the Hilbert space and applies the Lanczos algorithm to it. If your Hamiltonian has only two e'values, -1, 0, and +1, which are largely degenerate, then in a large Hilbert space it is likely that the initial random vector has no support on the ground state subpace; hence the algorithm can converge to a wrong e'value, e.g. 0, in this case.

To test the above hypothesis, let's give explicitly the initial vector `v0` to `eighs()`. To choose `v0` I fix the seed of the rng. Using `seed=0` gives one e'value 0 and the rest of the e'values -1; but using `seed=1` gives all e'values -1. More importantly, the results are now consistent between the different iterations of the loop. 

Hence the problem is with the initial vector for the Lanczos algorithm; if you give it an ill-posed Hamiltonian, and you're not careful enough about how you initialize the algorithm (i.e. the value of `v0`), you can get nonsensical results.

See this script to get an idea of what I just tried to explain in words above. 
[bug.txt](https://github.com/weinbe58/QuSpin/files/5742245/bug.txt)

**Comment by kaushman1996** [comment]
Thank you for your reply.  I understand, I should have investigated more.
