### ISSUE TITLE
Issues with construction of long range interaction spin-hamiltonian

### ISSUE THREAD

**Issue by srujans** [weinbe58/QuSpin#61]
Hello,

       I was trying to construct the long-range interaction spin-Hamiltonian mentioned below using Quspin library from reference "https://arxiv.org/pdf/1610.01244.pdf"

![spin](https://user-images.githubusercontent.com/12464481/31314353-6fadb0da-ac1c-11e7-9fb6-39318d7503a5.PNG)

[$h_{i}$, $h_{j}$ are numbers from uniform distribution to introduce disorder]

 So, I was just curious what if we want to write similar long-range interaction Hamiltonians, how to proceed using Quspin. 

I tried it but somehow Hamiltonian was not coming out right which I deduced from Energy level statistics.
 
I also attached my code below.  I really appreciate any constructive comments.

[spinmodel.txt](https://github.com/weinbe58/QuSpin/files/1366666/spinmodel.txt)

Thank you.

**Comment by mgbukov** [comment]
Hi srujans,

you can certainly do this Hamiltonian with QuSpin. I modified your code slightly below. Let's go in some of the steps in detail:

```
from quspin.tools import *
from quspin.operators import hamiltonian # Hamiltonians and operators
from quspin.basis import spin_basis_1d # Hilbert space spin basis
import numpy as np 
from numpy.random import *
import random as rando
```
The following line will keep the seed of the random number generator fixed (need to remove this once you are sure the code works)
`rando.seed(0) # fixes seed for debugging`

```
# model params
L=3 # system size
J=1.0
B=0.6 
w=0.1
alpha=1.5
```
Let's create the basis:

`basis = spin_basis_1d(L,pauli=True) `

Note that your model does not conserve parity (reflection w.r.t. middle of chain) since the randomness in the coefficient of the zz-term breaks it, so you cannot use `pblock`. Also, the x-term break magnetisation conservation so you cannot restrict to a single magnetisation sector. What you can do though is restrict to all even magnetisation sectors. Last, if u set `pauli=False` you are forcing QuSpin to use the Spin-1/2 matrices, and NOT the sigma matrices. Since u wrote the Hamiltonian using the sigma matrices, I set `pauli=True` (which is the default and can be omitted).

To define the random `h_z` field, you can use a list

`h_z=[-w+2.0*w*rando.uniform(0,1) for _ in range(L)]`

or even create the entire array of random numbers at once using `np.random.uniform()`. 

The site-coupling lists can be specified as follows

```
J_zz = [[J*(1.0+h_z[i]*h_z[j])/np.abs(i-j)**alpha,i,j] for i in range(L) for j in range(L) if i<j]
J_x = [[B,i] for i in range(L)] # PBC
```

Note first that you can use an if clause to incorporate the constraint `i<j` within the list comprehension. Python's really cool. Second, we don't need the modulo operator `%`, since the interaction is all-to-all, and similar for the single-particle term.

I think u got the Hamiltonian right. My advice is to always leave the symmetry checks on until u make sure u can safely turn them off. If u turn the checks off u may end up with a non-hermitian Hamiltonian if it doesn't obey the symmetries u request.

```
# opstr lists
static=[["zz",J_zz],["x",J_x]]
dynamic=[]
# build Hamiltonian
H=hamiltonian(static,dynamic,basis=basis,dtype=np.float64)
print(H.toarray())
```
Note the method `.toarray()` which allows you to print the Hamiltonian matrix.

Btw, we now have a [documentation](http://weinbe58.github.io/QuSpin/index.html) so support the package. We will have a new release very soon so make sure you update your version so you can access the new features. 

Hope this helps.

**Comment by srujans** [comment]
Hello Mgbukov,
                        Thanks a lot for your great efforts, I really appreciate it and also I apologise for such blunders in code. 
The overall reply of yours is really informative for me, especially I  the if condition insertion within the list and "toarray()" to print hamiltonian.
I am really thankful to you for your reply.
And I am really enjoying working and playing with Quspin.
Looking forward to new version!!!
