### ISSUE TITLE
How to write Fourier series present in Hamiltonian?

### ISSUE THREAD

**Issue by srujans** [weinbe58/QuSpin#88]
Hello Developers,
              My concern regarding this issue is that I was trying to write down the Hamiltonian given as

![image](https://user-images.githubusercontent.com/12464481/34077254-836d7bba-e325-11e7-9428-545cefb08191.png)

In this Hamiltonian, what mainly troubles me is the time-dependent Fourier part where summation index 'n'  is also present in time-exponential. How should I include this summation using Quspin specifically in time part? I tried to write down the complete code which I am attaching below, if possible from your tight schedule please have a look at it.

[code.txt](https://github.com/weinbe58/QuSpin/files/1565373/code.txt)

Please see: below is the paper link which I am following. A complete description of Hamiltonian is present at page 2.

https://arxiv.org/pdf/1702.06208.pdf

Also, One curious doubt: In MBL papers, many times they are based on the numerical study of correlation functions, like in above paper. Is there a possibility in the future about an update on correlation functions in Quspin?

Thanking you.
Srujan

**Comment by mgbukov** [comment]
Hi Srujan,

I think the following might work here. SInce the time-dependence doesn't have any spatial component, let's re-write the time-dependent part of the above Hamiltonian in the form

H(t) = H_{eff} + H_1(t)

H_1(t) = f(t)V + h.c.

where 

f(t) = \sum_{n\neq 0} \mathcal{J}_n(A/\omega) e^{-i n\omega t)
V = \sum_j c^\dagger_{j+1} c_j # using j for the lattice sites not to foncused it with the imaginary unit i

Notice that the operator V is non-hermitian, so you would have to use `check_herm=False` to create it with the `hamiltonian` constructor. 

U can decide how many harmonics to keep in the function f(t), which u define in the usual well (now also summing over the Fourier harmonics). 

The above implementation is simple and computationally efficient :)

**Comment by srujans** [comment]
Hello MGBukov,
Thanks a lot for the answer. I got the way. And I will open the new issue.
Srujan.
